services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./postgres/pg_hba.conf:/opt/postgres/pg_hba.conf:ro
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure:3

  postgres-migrator:
    container_name: migrate
    image: migrate/migrate:v4.18.1
    volumes:
      - ./postgres/migrations.sh:/usr/local/bin/migrations.sh
    entrypoint: /usr/local/bin/migrations.sh
    restart: no

  kreda-server:
    container_name: kreda-server
    image: kreda-server
    build:
      context: ./server
      target: base
      dockerfile: ./KredaServer.Presentation/Dockerfile
    volumes:
      - ./server:/workspace
      - ./certs/kreda-server:/certs:ro
    ports:
      - "5000:5000"
    entrypoint: ./KredaServer.Presentation/dev-entrypoint.sh
    restart: on-failure:3

  kreda-client:
    container_name: kreda-client
    image: kreda-client
    build:
      context: ./client
      target: base
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/workspace
    entrypoint: ./dev-entrypoint.sh
    restart: on-failure:3

volumes:
  postgres:
